//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the vicon_bridge package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __vicon_bridge__TF_DISTORTCONFIG_H__
#define __vicon_bridge__TF_DISTORTCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace vicon_bridge
{
  class tf_distortConfigStatics;
  
  class tf_distortConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(tf_distortConfig &config, const tf_distortConfig &max, const tf_distortConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const tf_distortConfig &config1, const tf_distortConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, tf_distortConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const tf_distortConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, tf_distortConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const tf_distortConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T tf_distortConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (tf_distortConfig::* field);

      virtual void clamp(tf_distortConfig &config, const tf_distortConfig &max, const tf_distortConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const tf_distortConfig &config1, const tf_distortConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, tf_distortConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const tf_distortConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, tf_distortConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const tf_distortConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 18 "../cfg/tf_distort.cfg"
      double tf_pub_rate;
//#line 19 "../cfg/tf_distort.cfg"
      bool tf_publish;
//#line 20 "../cfg/tf_distort.cfg"
      std::string tf_ref_frame;
//#line 21 "../cfg/tf_distort.cfg"
      std::string tf_frame_in;
//#line 22 "../cfg/tf_distort.cfg"
      std::string tf_frame_out;
//#line 23 "../cfg/tf_distort.cfg"
      int delay;
//#line 24 "../cfg/tf_distort.cfg"
      double position_scale;
//#line 25 "../cfg/tf_distort.cfg"
      std::string noise_type;
//#line 26 "../cfg/tf_distort.cfg"
      double sigma_roll_pitch;
//#line 27 "../cfg/tf_distort.cfg"
      double sigma_yaw;
//#line 28 "../cfg/tf_distort.cfg"
      double sigma_xy;
//#line 29 "../cfg/tf_distort.cfg"
      double sigma_z;
//#line 30 "../cfg/tf_distort.cfg"
      double random_walk_k_xy;
//#line 31 "../cfg/tf_distort.cfg"
      double random_walk_k_z;
//#line 32 "../cfg/tf_distort.cfg"
      double random_walk_sigma_xy;
//#line 33 "../cfg/tf_distort.cfg"
      double random_walk_sigma_z;
//#line 34 "../cfg/tf_distort.cfg"
      double random_walk_tau_xy;
//#line 35 "../cfg/tf_distort.cfg"
      double random_walk_tau_z;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("tf_distortConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const tf_distortConfig &__max__ = __getMax__();
      const tf_distortConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const tf_distortConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const tf_distortConfig &__getDefault__();
    static const tf_distortConfig &__getMax__();
    static const tf_distortConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const tf_distortConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void tf_distortConfig::ParamDescription<std::string>::clamp(tf_distortConfig &config, const tf_distortConfig &max, const tf_distortConfig &min) const
  {
    return;
  }

  class tf_distortConfigStatics
  {
    friend class tf_distortConfig;
    
    tf_distortConfigStatics()
    {
//#line 18 "../cfg/tf_distort.cfg"
      __min__.tf_pub_rate = 0.0;
//#line 18 "../cfg/tf_distort.cfg"
      __max__.tf_pub_rate = 250.0;
//#line 18 "../cfg/tf_distort.cfg"
      __default__.tf_pub_rate = 100.0;
//#line 18 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("tf_pub_rate", "double", 0, "rate at which tf publishes transforms. ", "", &tf_distortConfig::tf_pub_rate)));
//#line 19 "../cfg/tf_distort.cfg"
      __min__.tf_publish = 0;
//#line 19 "../cfg/tf_distort.cfg"
      __max__.tf_publish = 1;
//#line 19 "../cfg/tf_distort.cfg"
      __default__.tf_publish = 1;
//#line 19 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<bool>("tf_publish", "bool", 0, "determine if output will be published.", "", &tf_distortConfig::tf_publish)));
//#line 20 "../cfg/tf_distort.cfg"
      __min__.tf_ref_frame = "";
//#line 20 "../cfg/tf_distort.cfg"
      __max__.tf_ref_frame = "";
//#line 20 "../cfg/tf_distort.cfg"
      __default__.tf_ref_frame = "world";
//#line 20 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_ref_frame", "str", 0, "tf reference frame.", "", &tf_distortConfig::tf_ref_frame)));
//#line 21 "../cfg/tf_distort.cfg"
      __min__.tf_frame_in = "";
//#line 21 "../cfg/tf_distort.cfg"
      __max__.tf_frame_in = "";
//#line 21 "../cfg/tf_distort.cfg"
      __default__.tf_frame_in = "in";
//#line 21 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_frame_in", "str", 0, "tf input frame.", "", &tf_distortConfig::tf_frame_in)));
//#line 22 "../cfg/tf_distort.cfg"
      __min__.tf_frame_out = "";
//#line 22 "../cfg/tf_distort.cfg"
      __max__.tf_frame_out = "";
//#line 22 "../cfg/tf_distort.cfg"
      __default__.tf_frame_out = "tf_distort/out";
//#line 22 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("tf_frame_out", "str", 0, "tf output frame.", "", &tf_distortConfig::tf_frame_out)));
//#line 23 "../cfg/tf_distort.cfg"
      __min__.delay = 0;
//#line 23 "../cfg/tf_distort.cfg"
      __max__.delay = 1000;
//#line 23 "../cfg/tf_distort.cfg"
      __default__.delay = 0;
//#line 23 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<int>("delay", "int", 0, "delay [ms]. ", "", &tf_distortConfig::delay)));
//#line 24 "../cfg/tf_distort.cfg"
      __min__.position_scale = 0.01;
//#line 24 "../cfg/tf_distort.cfg"
      __max__.position_scale = 10.0;
//#line 24 "../cfg/tf_distort.cfg"
      __default__.position_scale = 1.0;
//#line 24 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("position_scale", "double", 0, "scale of the position measurement", "", &tf_distortConfig::position_scale)));
//#line 25 "../cfg/tf_distort.cfg"
      __min__.noise_type = "";
//#line 25 "../cfg/tf_distort.cfg"
      __max__.noise_type = "";
//#line 25 "../cfg/tf_distort.cfg"
      __default__.noise_type = "normal";
//#line 25 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<std::string>("noise_type", "str", 0, "noise distribution. Standard deviation in case for normal, max. in case for uniform distribution. ", "{'enum_description': 'An enum to set the noise distribution.', 'enum': [{'srcline': 11, 'description': 'normal distributed noise.', 'srcfile': '../cfg/tf_distort.cfg', 'cconsttype': 'const char * const', 'value': 'normal', 'ctype': 'std::string', 'type': 'str', 'name': 'NORMAL'}, {'srcline': 12, 'description': 'uniform distributed noise.', 'srcfile': '../cfg/tf_distort.cfg', 'cconsttype': 'const char * const', 'value': 'uniform', 'ctype': 'std::string', 'type': 'str', 'name': 'UNIFORM'}]}", &tf_distortConfig::noise_type)));
//#line 26 "../cfg/tf_distort.cfg"
      __min__.sigma_roll_pitch = 0.0;
//#line 26 "../cfg/tf_distort.cfg"
      __max__.sigma_roll_pitch = 2.0;
//#line 26 "../cfg/tf_distort.cfg"
      __default__.sigma_roll_pitch = 0.0;
//#line 26 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_roll_pitch", "double", 0, "std dev for roll and pitch [deg]. ", "", &tf_distortConfig::sigma_roll_pitch)));
//#line 27 "../cfg/tf_distort.cfg"
      __min__.sigma_yaw = 0.0;
//#line 27 "../cfg/tf_distort.cfg"
      __max__.sigma_yaw = 2.0;
//#line 27 "../cfg/tf_distort.cfg"
      __default__.sigma_yaw = 0.0;
//#line 27 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_yaw", "double", 0, "std dev for yaw [deg]. ", "", &tf_distortConfig::sigma_yaw)));
//#line 28 "../cfg/tf_distort.cfg"
      __min__.sigma_xy = 0.0;
//#line 28 "../cfg/tf_distort.cfg"
      __max__.sigma_xy = 1.0;
//#line 28 "../cfg/tf_distort.cfg"
      __default__.sigma_xy = 0.0;
//#line 28 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_xy", "double", 0, "std dev for x/y [m]. ", "", &tf_distortConfig::sigma_xy)));
//#line 29 "../cfg/tf_distort.cfg"
      __min__.sigma_z = 0.0;
//#line 29 "../cfg/tf_distort.cfg"
      __max__.sigma_z = 1.0;
//#line 29 "../cfg/tf_distort.cfg"
      __default__.sigma_z = 0.0;
//#line 29 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("sigma_z", "double", 0, "std dev for z [m]. ", "", &tf_distortConfig::sigma_z)));
//#line 30 "../cfg/tf_distort.cfg"
      __min__.random_walk_k_xy = 0.0;
//#line 30 "../cfg/tf_distort.cfg"
      __max__.random_walk_k_xy = 10.0;
//#line 30 "../cfg/tf_distort.cfg"
      __default__.random_walk_k_xy = 0.0;
//#line 30 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_k_xy", "double", 0, "gain for random walk disturbance in x/y axis.", "", &tf_distortConfig::random_walk_k_xy)));
//#line 31 "../cfg/tf_distort.cfg"
      __min__.random_walk_k_z = 0.0;
//#line 31 "../cfg/tf_distort.cfg"
      __max__.random_walk_k_z = 10.0;
//#line 31 "../cfg/tf_distort.cfg"
      __default__.random_walk_k_z = 0.0;
//#line 31 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_k_z", "double", 0, "gain for random walk disturbance in z axis.", "", &tf_distortConfig::random_walk_k_z)));
//#line 32 "../cfg/tf_distort.cfg"
      __min__.random_walk_sigma_xy = 0.0;
//#line 32 "../cfg/tf_distort.cfg"
      __max__.random_walk_sigma_xy = 20.0;
//#line 32 "../cfg/tf_distort.cfg"
      __default__.random_walk_sigma_xy = 0.0;
//#line 32 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_sigma_xy", "double", 0, "std dev for gauss markov process in x/y axis [m].", "", &tf_distortConfig::random_walk_sigma_xy)));
//#line 33 "../cfg/tf_distort.cfg"
      __min__.random_walk_sigma_z = 0.0;
//#line 33 "../cfg/tf_distort.cfg"
      __max__.random_walk_sigma_z = 20.0;
//#line 33 "../cfg/tf_distort.cfg"
      __default__.random_walk_sigma_z = 0.0;
//#line 33 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_sigma_z", "double", 0, "std dev for gauss markov process in x/y axis [m].", "", &tf_distortConfig::random_walk_sigma_z)));
//#line 34 "../cfg/tf_distort.cfg"
      __min__.random_walk_tau_xy = 1.0;
//#line 34 "../cfg/tf_distort.cfg"
      __max__.random_walk_tau_xy = 3000.0;
//#line 34 "../cfg/tf_distort.cfg"
      __default__.random_walk_tau_xy = 0.001;
//#line 34 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_tau_xy", "double", 0, "time constant for gauss markov process in x/y axis [s].", "", &tf_distortConfig::random_walk_tau_xy)));
//#line 35 "../cfg/tf_distort.cfg"
      __min__.random_walk_tau_z = 1.0;
//#line 35 "../cfg/tf_distort.cfg"
      __max__.random_walk_tau_z = 3000.0;
//#line 35 "../cfg/tf_distort.cfg"
      __default__.random_walk_tau_z = 0.001;
//#line 35 "../cfg/tf_distort.cfg"
      __param_descriptions__.push_back(tf_distortConfig::AbstractParamDescriptionConstPtr(new tf_distortConfig::ParamDescription<double>("random_walk_tau_z", "double", 0, "time constant for gauss markov process in z axis [s].", "", &tf_distortConfig::random_walk_tau_z)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<tf_distortConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<tf_distortConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    tf_distortConfig __max__;
    tf_distortConfig __min__;
    tf_distortConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const tf_distortConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static tf_distortConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &tf_distortConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const tf_distortConfig &tf_distortConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const tf_distortConfig &tf_distortConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const tf_distortConfig &tf_distortConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<tf_distortConfig::AbstractParamDescriptionConstPtr> &tf_distortConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const tf_distortConfigStatics *tf_distortConfig::__get_statics__()
  {
    const static tf_distortConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = tf_distortConfigStatics::get_instance();
    
    return statics;
  }

//#line 11 "../cfg/tf_distort.cfg"
      const char * const tf_distort_NORMAL = "normal";
//#line 12 "../cfg/tf_distort.cfg"
      const char * const tf_distort_UNIFORM = "uniform";
}

#endif // __TF_DISTORTRECONFIGURATOR_H__
